### PR TITLE
Fixes issue #15: Created learn more component and added routing to it

### PR DESCRIPTION
**Pull request by Sakshi-75**
Fixes issue #15 
Created learn more component and added routing to it.
Added the app description from the readme file as the page content.
Could not add styling as I could not run the application on my local.

### CODE REVIEW

**Comment by csgeeek** [comment]
> Could not add styling as I could not run the application on my local.

Were you facing any issues in running the project?

Feel free to reach out to me [Link](https://github.com/Yaswanth820/Yaswanth820)

Discord:- `csgeek#6882`

**Comment by Sakshi-75** [comment]
Hi @Yaswanth820 , I've updated the page content and added a back button as well. Please review and merge.

**Review by csgeeek — APPROVED** [review]
cool

**Review by csgeeek — APPROVED** [review]
lgtm

**Pull request merged**
